### PR TITLE
CB-12297 Support WKProcessPool for cookie sharing

### PR DESCRIPTION
**Pull request by anandvnath**
### Platforms affected

iOS

### What does this PR do?

Adds a shared WKProcessPool via static factory and use it in the  WKWebView created by this plugin. Any WKWebView created by cordova apps can utilize this shared WKProcessPool for enabling cookie sharing.

### What testing has been done on this change?

Added a unit test to check if the shared instance is correctly created. Testing the cookie sharing functionality is hard to do via unit test.

### Checklist
- [/] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [/] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [/] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by anandvnath** [comment]
@shazron Thanks for approving this.

Appreciate any updates on when you are planning to make this fix available?

Thanks
Anand

**Comment by shazron** [comment]
The next release perhaps in the next two weeks since I will be away next week. I'm trying to fix the CI failures for this repo first (they pass when manually run).

**Comment by shazron** [comment]
I've fixed the CI problem and would like this PR to be green before I pull it in. Can you rebase? It should re-test the PR automatically after.

**Comment by anandvnath** [comment]
Rebase done, CI is passing.

**Pull request closed without merging**
