### PR TITLE
Ionic changes to WKWebView (For Code Review only)

### PR DESCRIPTION
**Pull request by danbucholtz**
As of August 16th, 2016, this is not ready to be merged.  I am just creating this PR to facilitate dialogue and chat about the changes.

Thanks,
Dan
### Platforms affected

iOS
### What does this PR do?

Resolves some DOM exceptions and XHR challenges with WKWebView
### What testing has been done on this change?

We have tested it manually on iOS 9 and iOS 10 across several different Cordova apps.
### Checklist
- [x] [ICLA](http://www.apache.org/licenses/icla.txt) has been signed and submitted to secretary@apache.org.
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [x] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by shazron** [comment]
Thanks for this! I just merged #13, so can you rebase? I'll review after that is done.
Note that the CI auto builds your PR, and it has jshint errors: https://travis-ci.org/apache/cordova-plugin-wkwebview-engine/builds/152735998

**Comment by manucorporat** [comment]
Hi @shazron  sure thing! I take care of this :)

**Comment by shazron** [comment]
Hi,
Some issues I've encountered, pre-testing:

1. Can you prefix the issue with CB-10109 so it can be automatically tracked by the apache bots to https://issues.apache.org/jira/browse/CB-10109
2. All traces of "Ionic" have to be removed, in the docs or the code -- you'll have to rework the docs so that they are Cordova centric. All the contributors to this project (indeed any Apache project) are treated as if they are independent of any company and their contributions should reflect as such. Attribution is through the "Author" of the commit.
3. jshint errors that need to be resolved:
```
src/ios/xhr.js: line 55, col 8, Creating global 'for' variable. Should be 'for (var property ...'.
src/ios/xhr.js: line 58, col 8, Creating global 'for' variable. Should be 'for (var property ...'.
src/ios/xhr.js: line 55, col 8, 'property' is not defined.
src/ios/xhr.js: line 56, col 20, 'property' is not defined.
src/ios/xhr.js: line 58, col 8, 'property' is not defined.
src/ios/xhr.js: line 59, col 9, 'property' is not defined.
src/ios/xhr.js: line 59, col 64, 'property' is not defined.
src/ios/xhr.js: line 60, col 16, 'property' is not defined.
src/ios/xhr.js: line 60, col 40, 'property' is not defined.
```
4. The contributor, in this case, @manucorporat, **must** file an [iCLA](https://www.apache.org/licenses/icla.txt) since this is a non-trivial contribution. This is required. I did not find one that was filed already.
5. The contributor's employer, in this case @driftyco, should file a [CCLA](https://www.apache.org/licenses/cla-corporate.txt). Note that this is **not** required, but see this [FAQ item](http://www.apache.org/legal/resolved.html#are-contributors-required-to-sign-a-ccla) on why its a good idea (particularly for the committer).

I'll proceed with reviewing the actual functionality of the code next week, unless there are any blockers to  issues 2, 4 and 5 that I have raised.

**Comment by briananderson1222** [comment]
Nice work! Due to some problems with WKWebView in iOS9 namely https://issues.apache.org/jira/browse/CB-10732?jql=project%20%3D%20CB%20AND%20labels%20%3D%20wkwebview-known-issues could it be considered to make the fallback customizable.. like if we wanted iOS9 to be able to fallback to UIWebView but iOS10 to use WKWebView?

**Comment by shazron** [comment]
@briananderson1222 this is a separate feature. currently we don't offer granularity for the fallback. could you file an issue at issues.cordova.io ? Thanks!

**Comment by jlchereau** [comment]
Definitely ++1 for this one.

https://github.com/kidoju/Kidoju-Mobile:
1) Loads a script library as text from a local file using $.ajax.
2) Executes a series of functions in web workers using this library.

(1) would fail with latest https://github.com/apache/cordova-plugin-wkwebview-engine but would succeed with latest https://github.com/driftyco/cordova-plugin-wkwebview-engine.git as of today.

What is the roadmap / ETA for merging Ionic's PR?

**Comment by shazron** [comment]
@jlchereau This PR cannot be merged as is, since there are issues to be resolved. Furthermore, this PR has been set up as a discussion PR to discuss changes and is not ready for contribution. Contribution to Apache in a cleaned up PR is up to the PR submitter.

**Comment by cordova-qa** [comment]
Cordova CI Build has one or more failures. 

**Commit**     - [Link](https://github.com/apache/cordova-plugin-wkwebview-engine/pull/15/commits/20611456a86f22ab4ce7b75ff53887910eea2bd0)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-wkwebview-engine-pr/4/)

 0 tests run, 0 skipped, 0 failed.

**Comment by alsorokin** [comment]
Please disregard this test result. I was just testing a job and it went rogue.

**Comment by cordova-qa** [comment]
Cordova CI Build has one or more failures. 

**Commit**     - [Link](https://github.com/apache/cordova-plugin-wkwebview-engine/pull/15/commits/09a47d8d4e8db68a2211e93337debc7e6fd53031)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-wkwebview-engine-pr/14/)

 0 tests run, 0 skipped, 0 failed.

**Comment by cordova-qa** [comment]
Cordova CI Build has one or more failures. 

**Commit**     - [Link](https://github.com/apache/cordova-plugin-wkwebview-engine/pull/15/commits/c006d6673d8c2ab39536a55055062df635c4afdd)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-wkwebview-engine-pr/15/)

 0 tests run, 0 skipped, 0 failed.

**Comment by cordova-qa** [comment]
Cordova CI Build has one or more failures. 

**Commit**     - [Link](https://github.com/apache/cordova-plugin-wkwebview-engine/pull/15/commits/5a67fd57e06c8a44f43a332a379d5e13ef2a7d1a)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-wkwebview-engine-pr/17/)

 0 tests run, 0 skipped, 0 failed.

**Comment by cordova-qa** [comment]
Cordova CI Build has one or more failures. 

**Commit**     - [Link](https://github.com/apache/cordova-plugin-wkwebview-engine/pull/15/commits/56df01a38843445eb8c83c11af24e34267789259)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-wkwebview-engine-pr/20/)

 0 tests run, 0 skipped, 0 failed.

**Comment by cordova-qa** [comment]
Cordova CI Build has one or more failures. 

**Commit**     - [Link](https://github.com/apache/cordova-plugin-wkwebview-engine/pull/15/commits/a2049be5f9d24ac27bf9aaed260f494f11ca5b23)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-wkwebview-engine-pr/21/)

 0 tests run, 0 skipped, 0 failed.

**Comment by cordova-qa** [comment]
Cordova CI Build has one or more failures. 

**Commit**     - [Link](https://github.com/apache/cordova-plugin-wkwebview-engine/pull/15/commits/afff6b2c99ed6d4d9c7168af7b0206d9c25951e9)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-wkwebview-engine-pr/22/)

 0 tests run, 0 skipped, 0 failed.

**Comment by cordova-qa** [comment]
Cordova CI Build has one or more failures. 

**Commit**     - [Link](https://github.com/apache/cordova-plugin-wkwebview-engine/pull/15/commits/5e78926344fa07a89ff9dd5890baf8c14e0d2a67)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-wkwebview-engine-pr/24/)

 0 tests run, 0 skipped, 0 failed.

**Comment by cordova-qa** [comment]
Cordova CI Build has one or more failures. 

**Commit**     - [Link](https://github.com/apache/cordova-plugin-wkwebview-engine/pull/15/commits/ff18817cac25f9be6c652756fb84f8be080fb3cd)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-wkwebview-engine-pr/25/)

 0 tests run, 0 skipped, 0 failed.

**Comment by shazron** [comment]
Please close this PR, I consider it abandoned and it does not seem to serve any purpose for Cordova currently.

**Comment by timbru31** [comment]
Sorry for the revive/bump but has there been any dialogue recently to merge the Ionic changes back into the upstream Apache project? They are drifting more and more apart...

**Pull request closed without merging**
