### PR TITLE
Readme update

### PR DESCRIPTION
**Pull request by laidig**
I had a lot of trouble understanding why my app would not load. It turns out that the answer was at the bottom of the README. I've the moved required configuration up to the installation section and made some minor edits. This should help some other users.

### CODE REVIEW

**Comment by pke** [comment]
Wow! I cannot stress how important that readme update is. It should be even made more prominent that the `deviceready` event may never fire, if the plugin is included in a cordova app but never configured. 

We spent one (!) week trying to out find out why the app would randomly not start.
This should be merged as soon as possible and the plugin should behave with that config by default, meaning nobody should need to set those preferences in the first place.

**Comment by daserge** [comment]
@pke, are these config.xml updates resolving the https://issues.apache.org/jira/browse/CB-11089?

**Comment by laidig** [comment]
@daserge it's possible. There are a number of other reasons that the deviceReady event does not fire, this is one of them.

**Comment by pke** [comment]
@daserge no, they do not solve this problem. I have not set splashscreen delay to 0, fade to 0 and the darn screen is still NOT hiding when hide() is called. How can such a simple operation be so broken?

**Comment by pke** [comment]
@laidig the `deviceready` event does fire, the app starts fine and is running *behind* the splashscreen all along.

**Comment by laidig** [comment]
If deviceready fires, then wkwebview loaded, so this would not be the
problem.

dumb question: have you added and removed the plugin?

**Comment by shazron** [comment]
Those settings are set by the CLI from the plugin.xml. They are explicitly put in the README to show what permissions are needed by the plugin.

It might be a splashscreen bug.

**Comment by pke** [comment]
In my case the problem was that the wkwebview does not work well with async loaded script files.
I had

```html5
<script src="cordova.js" async/>
<script src="bundle.js" async/>
```

As soon as I removed the async attribute (after one week of trying other things) everything worked, including the splashscreen. I think the splashscreen uses the message queue (event loop) to postpone some of its actions (when fading out) and this collides with the `async` attribute and creates a race-condition. It seems like a bug in wkwebview to not handle `async` script loading properly.

**Comment by laidig** [comment]
@shazron any testing that I could help with?

**Comment by shazron** [comment]
@laidig it is not set in your root config.xml, but the platform's config.xml (under platforms/ios/projectname/config.xml) since the settings are only for the ios platform.

thanks @pke for that information. do you mind adding a bug for it, so I can tag it as a known issue?

**Comment by pke** [comment]
@shazron sure: https://issues.apache.org/jira/browse/CB-11469 
I guess its historical reasons why issues are not tracked directly here in GH?

**Comment by shazron** [comment]
@pke thanks! Historical, and permissions granularity issues. Apache is working on it so we can use GH issues, but that's still a ways off (in testing phase).

**Pull request closed without merging**
