### PR TITLE
CB-13529: Don't run Android tests

### PR DESCRIPTION
**Pull request by jcesarmobile**
### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by alsorokin** [comment]
The build was flaky, wasn't it?
I knew I shouldn't've added it in the first place 🐛

**Comment by jcesarmobile** [comment]
Yeah, and the plugin is iOS only, so it's not useful to run Android tests on it

**Comment by alsorokin** [comment]
We weren't running tests, we were just building it to make sure that project that has this plugin installed wouldn't fail Android build.
I wonder if this check makes any sense at all 😜

**Comment by jcesarmobile** [comment]
The plugin.xml only have iOS platform, so it shouldn't affect other platforms builds, but who knows.

It was failing, I don't remember the error, but it was previous to adding the plugin

**Pull request merged**
