### PR TITLE
fix(ios): fix keyboard displacement bug in iOS 12 WKWebView

### LINKED ISSUE #71: When closing keyboard, content doesn't scroll back leaving ehite space in place of keyboard
Hi, this issue started with latest osx/xcode updates, nothing changed in code, and exactly same code and cordova/wkwebivew version worked fine a month ago. Now building the same code gives following issue, it is also described here:

https://forum.mendixcloud.com/link/questions/91916

Removing wkwebview fixes this issue

(I am not using any custom keyboard plugins)

Screenshots:
img_0019

img_0017

img_0018

Here's a video of this happening:

https://drive.google.com/file/d/1PXkIu2Q5b0GDSrzKyrm_okyg2ciCVewK/view?usp=sharing

### PR DESCRIPTION
**Pull request by mwchambers**
Using solution from here:
https://github.com/ionic-team/cordova-plugin-ionic-webview/pull/201/commits

fix #71

### CODE REVIEW

**Comment by tpneumat** [comment]
any hope to see this included so I don't have to hack the plugin too?

**Comment by Goregut** [comment]
Curious about this too. Just start experiencing the keyboard issue as well.

**Comment by shahdeep1989** [comment]
Why It's not fixed yet? Can any one provide me solution for this issue?

**Comment by janpio** [comment]
CI, please rerun tests.

**Comment by janpio** [comment]
And once more.

**Comment by ChildishForces** [comment]
Can we look forward to this soon, given that all tests are passing?

**Comment by janpio** [comment]
Not from me, I don't review and approve (and merge) PRs that I don't fully understand (as is the case for all iOS code). Some other contributor will have to do that, I just made sure the tests were run successfully.

(You can of course just use https://github.com/mwchambers/cordova-plugin-wkwebview-engine from github directly until then.)

**Comment by joacim-boive** [comment]
I don’t think this is a valid fix.

If the page is scrolled, like when the entire doesn’t fit in the view, the page will scroll to the top each time you interact with an input-element. This will quickly become extremely tiresome… ;)

This means: Click a dropdown, select a value, <Scroll to top>, scrolling down, select another field, close the keyboard, <Scroll to top>, rinse-and-repeat.

**Comment by mwchambers** [comment]
> I don’t think this is a valid fix.
> 
> If the page is scrolled, like when the entire form doesn’t fit in the view, the page will scroll to the top each time you interact with an input-element. This will quickly become extremely tiresome… ;)
> 
> This means: Click a dropdown, select a value, [ ScrolledToTop ], scrolling down, select another field, close the keyboard, [ ScrolledToTop ], rinse-and-repeat.

I had not noticed this, however you are absolutely correct!

I've just tested it and it does behave how you've described. I guess https://github.com/ionic-team/cordova-plugin-ionic-webview/ must have the same issue. 

Unfortunately I don't have the experience required to help with this any further with this.

**Comment by dpogue** [comment]
This is resolved in iOS 13.4. For earlier versions of iOS, using the [cordova-plugin-wkkeyboardfix](https://www.npmjs.com/package/cordova-plugin-wkkeyboardfix) is probably the best solution. We will not be making any changes to Cordova to address this bug.

**Pull request closed without merging**
