### PR TITLE
CB-10269: Replace cordova exec only when present in wkwebview

### PR DESCRIPTION
**Pull request by jamesandersen**

### CODE REVIEW

**Comment by hassankhan** [comment]
+1 can this be merged soon please? :+1:

**Comment by dpogue** [comment]
It has already been merged in https://github.com/apache/cordova-plugin-wkwebview-engine/commit/faa9d877045d8baf8afdfd0d8689389ec240e2e4

**Comment by hassankhan** [comment]
Ah my mistake, I assumed the error I was getting was related to this.

**Comment by hassankhan** [comment]
Is it possible for a new release to be tagged?

**Comment by andres-torres-marroquin** [comment]
I also thought it wasn't merged, how can we know that? I'm unfamiliar on how this is handled.

**Comment by jcesarmobile** [comment]
check the jira issue
https://issues.apache.org/jira/browse/CB-10269
Commit faa9d877045d8baf8afdfd0d8689389ec240e2e4 in cordova-plugin-wkwebview-engine's branch refs/heads/master from James Andersen
[ https://git-wip-us.apache.org/repos/asf?p=cordova-plugin-wkwebview-engine.git;h=faa9d87 ]

Or check the main page https://github.com/apache/cordova-plugin-wkwebview-engine, you can see.
jamesandersen committed with shazron CB-10269: Replace cordova exec only when present in wkwebview


It should have closed this, but sometimes fails.

**Comment by hassankhan** [comment]
I believe it is merged just fine, but there hasn't been a new release of the plugin on npm, so anybody trying to use the latest version won't get this fix at the moment.

**Comment by IvanKarpan** [comment]
IMHO without a release to npm this whole WKWebView support of Cordova is pretty not usable at all ATM...

**Comment by jcesarmobile** [comment]
It's not on NPM yet, plugin releases take time.
Anybody using cordova can install from github, they don't have to wait for the NPM release.

**Comment by hassankhan** [comment]
True, but a new release is usually only an `npm publish` away, unless I'm mistaken? :)

**Comment by dpogue** [comment]
This is part of an Apache Software Froundation project, so any release needs to follow the ASF guidelines including a 48-hour voting period with 3 votes of approval on the mailing list.

**Comment by shazron** [comment]
@jamesandersen can you close this? it came out in the 1.0.2 release of the plugin

**Pull request closed without merging**
