### PR TITLE
CB-11554 - too 'brutal' app reload when title is empty

### PR DESCRIPTION
**Pull request by shazron**

### CODE REVIEW

**Comment by mccraigmccraig** [comment]
that all looks reasonable - i'll start testing it

**Comment by pwbs** [comment]
Anyone has an idea why I still encounter `about:blank` white screen of death?
It's quite hard to reproduce, it took me months before I could observe it with a Safari-inspectable version (so I could be sure it was a `about:blank` and not something else). It's even harder to observe in an Xcode-inspectable environment...

**Comment by mccraigmccraig** [comment]
@pwbs i think i saw this once too - though i have never been able to reproduce it in an inspectable environment

my first hypothesis would be that the WKWebView content process is dying some time after the `onAppWillEnterForeground` has made it's check, and since there is only a single check WSOD results

assuming you can reproduce the problem, what happens if, after WSOD, you background then foreground the app ? does it recover ?

**Comment by pwbs** [comment]
I've just observed it with a non-inspectable version: it's not recovering after back/foregrounding the app. :-/

**Comment by mccraigmccraig** [comment]
hmm - that would seem to indicate that it is a different bug, or that the WSOD has some other URL than `about:blank` ?

**Comment by pwbs** [comment]
Since it's a non-inspectable version, I can't be sure that it's actually `about:blank`, although I'd bet it is.

(I'm using iOS10 and with the inspectable versions I build with Xcode 8.{0,1} systematically crash when the user wants to upload a file; so it's not convenient at all to use those versions. Hence, the non-inspectable versions are built using Xcode 7; but I can't transfer them to my iOS10 iPhone because iOS10 is not supported on Xcode 7...)

**Comment by mccraigmccraig** [comment]
if it is `about:blank` that would mean one of

1. the `onAppWillEnterForeground` callback isn't firing 
2. there is a bug in the `onAppWillEnterForeground` callback https://github.com/apache/cordova-plugin-wkwebview-engine/blob/master/src/ios/CDVWKWebViewEngine.m#L129
3. the `reload` method doesn't work

if it's `[1]` or `[3]` i'll be flummoxed. it could be `[2]` but i can't spot anything by visual inspection

i think some more information is needed somehow

**Comment by pwbs** [comment]
I've just witnessed it again: this time there's no doubt that it's `about:blank`. 

However this time I have some weird messages in Safari's console:
screen shot 2016-12-22 at 17 37 59

**Comment by mccraigmccraig** [comment]
so that's pretty occasional then, which will make it hard to track down (i haven't seen WSOD at all recently)

my approach when i first worked on this was to fork this repo and create a build with debug logging wherever i thought it might be useful, wait for the bug to occur and then immediately grab the console logs off of my phone

can you do that ? put some logging in the `onAppWillEnterForeground` callback etc

**Comment by pwbs** [comment]
@mccraigmccraig thank you for your reply. I'll try to find some time for that next month...

**Comment by alexfoxy** [comment]
I am having an odd issue where my view is reloading but my view remains blank. If I inspect it using safari I can see there is a DOM and I can see the elements being highlighted on the device when I hover over them. 

screen shot 2017-01-16 at 09 16 04

I can reproduce fairly easily. Any suggestions?

**Pull request closed without merging**
