### PR TITLE
Handle opening links in new window

### PR DESCRIPTION
**Pull request by srgpqt**
Makes links with target="_blank" behave as expected.

### CODE REVIEW

**Comment by srgpqt** [comment]
No longer relevant.

**Comment by rayshan** [comment]
Hi @srgpqt, why is it no longer relevant? Seems like we still have to do `window.open` instead of `target="_blank"`.

**Comment by srgpqt** [comment]
target="_blank" worked for me in the iOS 9.2 simulator. I'll do some more testing.

**Comment by rayshan** [comment]
Thanks. By "new window", do you mean links are opening in Safari as a new tab when you use `target="_blank"`?

FYI We've been using https://github.com/apache/cordova-plugin-inappbrowser and `window.open` to open links in the in-app-browser.

**Comment by srgpqt** [comment]
Yes, links are opening in Safari as a new tab when I use target="_blank" on <a> elements.

I'm not using the InAppBrowser plugin.

**Comment by rayshan** [comment]
Thanks for the confirmation! We'll try this as well.

**Pull request closed without merging**
