### PR TITLE
[CB-11818] Avoid retain cycle caused by WKUserContentController retaining its message handler

### PR DESCRIPTION
**Pull request by lucatorella**
### Platforms affected
iOS

### What does this PR do?
This PR breaks the retain cycle caused by WKUserContentController retaining its message handler. This retain cycle would cause apps that create different CDVViewController instances to leak memory. For instance if you have a navigation controller, and you push a CDVViewController instance and then you go back, the view controller just pulled out of the stack is not deallocated.

https://issues.apache.org/jira/browse/CB-11818

### What testing has been done on this change?
I tested that the message from javascript are still passed. I think it's enough.

### Checklist
- [x] [ICLA](http://www.apache.org/licenses/icla.txt) has been signed and submitted to secretary@apache.org.
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [ ] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [x] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by shazron** [comment]
Where's the JIRA issue? Prefix it to the title for automated tracking.

**Comment by shazron** [comment]
Found it - CB-11818. Unfortunately I can't edit the issue title, can you please update it. Thanks!

**Comment by lucatorella** [comment]
Sorry, just updated the title

**Comment by shazron** [comment]
Do you know if this was fixed in iOS 10?

**Comment by lucatorella** [comment]
I haven't checked. I can easily check next week when I've access to a Mac again 🌴

**Comment by lucatorella** [comment]
It was not fixed

**Pull request closed without merging**
